# Generated by Django 4.0.4 on 2022-08-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('internal', models.BooleanField(default=True)),
                ('theme', models.IntegerField()),
                ('redirectTo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=2000)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.button')),
            ],
        ),
    ]
