# Generated by Django 4.0.4 on 2022-08-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_homepage_button_homepage_button_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
