# Generated by Django 4.0.4 on 2022-08-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_homepage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='button_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_1', to='api.button'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_2', to='api.button'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_3', to='api.button'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
